name: Java CI with Maven (TCC)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

env:
  TC_CLOUD_TOKEN: ${{ secrets.TC_CLOUD_TOKEN }}

jobs:
  build:
    name: "Test with ${{ matrix.os }}"
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Setup testcontainers-cloud
        uses: atomicjar/testcontainers-cloud-setup-action@main
      - uses: actions/setup-java@v3
        with:
          java-version: '8.0.345'
          distribution: temurin
      - name: Build with Maven
        run: mvn -V -B verify
